# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee0a7abc590223ad5ac432ac741363704d10f51d8a43537cd58eb525194f76efa1efdd99331756c8f2faa5a046904de2f72e6558c92235f587c36223afceed8a

test:
  secret_key_base: 7a63cd238252d869b097a6dc68fc692034c0d65fef2b5fdcd0d368d36b3da76e397c0cc04a79d22b0cd6c5ed60c18a4e215141afdaa1b33983179930d5f32d0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
